### ISSUE TITLE
Can you provide a non-bundle example?

### ISSUE THREAD

**Issue by Thundros** [mezzanine510/wilderness#1] opened 2019-06-30 01:38 UTC
Hi, @mezzanine510 ! First off, I'd like to start by saying, EXCELLENT job on this project, PLEASE keep up the GREAT work! :)

Secondly, can you please compile a non-bundle example so I can study the way this project works?

Thank You!

**Comment by mezzanine510** [comment] 2019-06-30 03:04
Hey @Thundros , thanks for the kind words! You've inspired me to update the README.md to make usage clearer, and though not that's directly related to your request, I mention the steps to bundle the project there. You'll notice the bundling step is `npm run start`. You can view all of the pre-bundle source code in the `src` folder. I used CommonJS imports, and you'll want to start with `index.js`, where I import all of the modules and use `init()` to actually launch the app. You should be able to work backwards from there! Let me know if this helped.

**Comment by Thundros** [comment] 2019-06-30 04:21
@mezzanine510 : I actually don't know ES6 at all. I only know ES5. So some kind of small demo that is the same thing as the ES6 demo would be great if possible! :)

**Comment by mezzanine510** [comment] 2019-06-30 04:48
You can `git checkout 774203f03f32c3b9093987de46b5563247e5db74` to check a much earlier version of the project, with most features you'd probably be interested in intact (maybe not camera movement). Check `/src/scripts/index.js`, and you'll see most of the code before I started using CommonJS modules too extensively. All you would really need to know from there is that the code in the other 2 files in the `/src` folder have been imported to `index.js`. To be more specific `gui-controls.js` provides a simple gui I built to help navigate around the scene, and `model-manager.js` provides the paths and positions of the models being loaded into the scene. Functionality of the scene is all contained withing `index.js`. You should be able to just fiddle around with the code in there to see how things work.

**Comment by Thundros** [comment] 2019-06-30 21:16
This git checkout function didn't work. It returned : 

`git checkout 774203f03f32c3b9093987de46b5563247e5db74
`fatal: not a git repository (or any of the parent directories): .git

**Comment by mezzanine510** [comment] 2019-06-30 21:28
Looks like you aren't in a git repository, so you must not be in the right root folder when calling the git checkout.

**Comment by Thundros** [comment] 2019-07-03 16:20
I tried that. It didn't work. :(

**Comment by mezzanine510** [comment] 2019-07-03 18:24
Can you walk me through the steps you're taking, starting from the `git clone` of the repo?

**Comment by Thundros** [comment] 2019-07-03 20:02
Well, I downloaded the repo as a zip file from github, but then when I try to do npm run build, it appears to be missing dependencies. When I do "npm install .", it downloads the dependencies, but when I go to compile it again, I get a compilation error. If you would like to see a screen shot of said error(s), please let me know.

Thanks!

**Comment by Thundros** [comment] 2019-07-06 06:06
@mezzanine510 would you like a screenshot?

**Comment by mezzanine510** [comment] 2019-07-07 23:49
> Well, I downloaded the repo as a zip file from github, but then when I try to do npm run build, it appears to be missing dependencies. When I do "npm install .", it downloads the dependencies, but when I go to compile it again, I get a compilation error. If you would like to see a screen shot of said error(s), please let me know.
> 
> Thanks!

By design, the downloaded ZIP won't include the git repository (which means it won't include any of its history). For this reason, you'll want to make sure you `git clone` the repo, not just download the zip. After cloning the repo, you'll have access to the entire commit history. Don't forget to `npm install` after you clone it. This should resolve all of the problems you're having.

Let me know if this works, and then I'll go ahead and close this thread!

**Comment by mezzanine510** [comment] 2019-07-10 18:05
@Thundros Did this solve the issue?

**Comment by Thundros** [comment] 2019-07-11 08:01
I don't know what exactly to put after 'git clone'

**Comment by mezzanine510** [comment] 2019-07-15 22:25
@Thundros I'll direct you to the guide on how to clone repos: 

https://help.github.com/en/articles/cloning-a-repository

**Comment by Thundros** [comment] 2019-07-15 23:45
Hi @mezzanine510 this is an AWESOME demo! Please keep up the GREAT work! <3

**Comment by mezzanine510** [comment] 2019-07-16 00:52
Appreciate it! I'll go ahead and close this issue since it sounds like you got things working.

**Closed by mezzanine510** 2019-07-16 00:52 UTC
Labels: help wanted
